# Generated by Django 3.1.7 on 2021-02-20 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20210220_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user',
            new_name='author',
        ),
    ]
